### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by apan65** [degenerated1123/REGoth#21]
The engine crashing if launch game with the second monitor in intel hd

**Comment by degenerated1123** [comment]
Is this on windows?

I'll enable D3D11 support for that then, since OpenGL really sucks on Intel HD.

Is there anything helpful in the output-log?

**Comment by apan65** [comment]
Windows, discrete graphics card rx480, in latest nightly i have this http://clip2net.com/clip/m11339/7ae5d-clip-115kb.jpg

**Comment by ousnius** [comment]
@degenerated1123:
Did you validate the shaders with the Khronos reference compiler yet?

**Comment by ousnius** [comment]
@apan65:
Did you try turning off MSI Afterburner/RivaTuner?

**Comment by apan65** [comment]
@ousnius
Yeah, it's definitely because of afterburner

**Comment by degenerated1123** [comment]
I have noticed other people having similar issues but without using AfterBurner (including myself, sorf of, on a different machine), which all can be fixed by a simple modification of the shader-source.

Unfortunately I don't have access to the shader-sources right now (should really upload them to the repo...), but I will fix it when I get home again.

In the meantime, you can just copy the ones from nightly-1.30.

**Comment by degenerated1123** [comment]
Shaders should be fixed.
